---
blank_issues_enabled: false

contact_links:
  - name: â“ Have a question?
    url: https://github.com/kloudkit/ws-meta/discussions/new?category=q-a
    about: Ask your questions in the GitHub Discussions.

  - name: ðŸ“š Documentation
    url: https://ws.kloudkit.com
    about: >-
      The full guide, including advanced usage and API reference,
      is available on the website
